# Generated by Django 3.2.8 on 2021-11-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_addapartment_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addapartment',
            old_name='Phone',
            new_name='OPhone',
        ),
        migrations.RemoveField(
            model_name='addapartment',
            name='area',
        ),
        migrations.AddField(
            model_name='addapartment',
            name='RPhone',
            field=models.CharField(default='1', max_length=800),
        ),
    ]
