# Generated by Django 3.2.8 on 2021-11-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211123_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addapartment',
            name='share',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
