# Generated by Django 3.2.8 on 2021-11-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_addapartment_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='addapartment',
            name='stno',
            field=models.PositiveIntegerField(default='2'),
        ),
    ]
